add initramfs resize hook

diff --git a/calaos-os/initramfs/hook_run_calaos b/calaos-os/initramfs/hook_run_calaos
--- a/calaos-os/initramfs/hook_run_calaos
+++ b/calaos-os/initramfs/hook_run_calaos
@@ -1,47 +1,107 @@
-#!/usr/bin/ash
+#!/bin/sh
+set -e
 
-# args: partition device (/dev/sda1)
-get_device_from_part() {
-    local part="${1}"
-    part=${part#/dev/}
-    local disk=$(readlink /sys/class/block/$part)
-    disk=${disk%/*}
-    disk=/dev/${disk##*/}
-    echo $disk
-}
+# Taken and adapted for Calaos from: https://packages.debian.org/bookworm/cloud-initramfs-growroot
 
-run_hook() {
-    local rootfs_dev=$(resolve_device "$root"); # resolve devices for blkid
+PREREQS=""
+case $1 in
+    prereqs) echo "${PREREQS}"; exit 0;;
+esac
 
-    if [ "$LABEL" = "live" ] || [ "$LABEL" = "live-efi" ]
-    then
-        msg ":: Entering Calaos OS Hook"
+. /scripts/functions
 
-        if [[ "$rootfs_dev" ]]
-        then
-            msg ":: Found rootfs on device: $rootfs_dev"
+msg() { echo "GROWROOT:" "$@" ; }
+fail() { [ $# -eq 0 ] || msg "$@"; exit 1; }
 
-            local uuid=$(echo $rootfs_dev | cut -d/ -f5)
-            msg ":: Found UUID: $uuid"
+# do nothing if already resized
+if [ ! -f /etc/calaos-resize ]; then
+	[ -f "${rootmnt}$f" ] && exit 0
+fi
 
-            local dev=$(blkid --uuid $uuid)
-            msg ":: Found rootfs dev: $dev"
+# figure out what disk ROOT is on
+{ [ ! -L "${ROOT}" ] && rootdev=${ROOT} || rootdev=$(readlink -f "${ROOT}") ; } ||
+	fail "failed to get target of link for ${ROOT}"
 
-            #rootfs is partition 2
-            local partnum=2
-            local rootdisk=$(get_device_from_part ${dev})
+case "${rootdev}" in
+	*[0-9]) : ;;
+	# the root is a disk, not a partition (does not end in a digit)
+	# no need to do anything in this case, kernel already knows the full size.
+    *) exit 0;;
+esac
 
-            msg ":: Found rootfs disk: $rootdisk"
+# remove all consective numbers from the end of rootdev to get 'rootdisk'
+rootdisk=${rootdev}
+while [ "${rootdisk%[0-9]}" != "${rootdisk}" ]; do
+	rootdisk=${rootdisk%[0-9]};
+done
+partnum=${rootdev#${rootdisk}}
 
-            #check if we need to resize rootfs partition to USB drive
-            if out=$(growpart --dry-run "${rootdisk}" "${partnum}") ; then
-                msg ":: Resizing rootfs to fill disk"
-                growpart --update auto "${rootdisk}" "${partnum}"
-                sleep 1
-                e2fsck -pf "${dev}"
-                sleep 1
-                resize2fs "${dev}"
-	        fi
-        fi
-    fi
-}
+# account for devnameNpP devices (like mmcblk0p1).
+if [ "${rootdisk%[0-9]p}" != "${rootdisk}" ] &&
+	[ -b "${rootdisk%p}" ]; then
+	rootdisk="${rootdisk%p}"
+fi
+
+# if the basename of the root device (ie 'xvda1' or 'sda1') exists
+# in /sys/block/ then it is a block device, not a partition
+# (xen xvda1 is an example of such a funny named block device)
+[ -e "/sys/block/${rootdev##*/}" ] && exit 0
+
+# if growpart fails, exit.
+# we capture stderr because on success of dry-run, it writes
+# to stderr what it would do.
+out=$(growpart --dry-run "${rootdisk}" "${partnum}" 2>&1) ||
+	{ msg "${out}"; exit 1; }
+
+# if growpart would change something, --dry-run will write something like
+#  CHANGE: partition=1 start=2048 old: size=1024000 end=1026048 new: size=2089192,end=2091240
+# anything else, exit
+case "${out}" in
+	CHANGE:*) :;;
+	*) exit 0;;
+esac
+
+# There was something to do, unmount and resize
+umount "${rootmnt}" ||
+	fail "failed to umount ${rootmnt}";
+
+# Wait for any of the initial udev events to finish
+# This is to avoid any other processes using the block device that the
+# root partition is on, which would cause the sfdisk 'BLKRRPART' to fail.
+udevadm settle --timeout ${ROOTDELAY:-30} ||
+	error "GROWROOT: WARNING: udevadm settle prior to growpart failed"
+
+if out=$(growpart "${rootdisk}" "${partnum}" 2>&1); then
+	case "$out" in
+		CHANGED:*)
+            echo "GROWROOT: $out"
+            sleep 1
+            e2fsck -pf "${rootdev}"
+            sleep 1
+            resize2fs "${rootdev}"
+            ;;
+    	NOCHANGE:*)
+			echo "GROWROOT: WARNING: expected to grow partition, but did not";;
+		*) echo "GROWROOT: unexpected output: ${out}"
+	esac
+else
+	echo "GROWROOT: WARNING: resize failed: $out"
+fi
+
+# Wait for the partition re-read events to complete 
+# so that the root partition is available when we try and mount it.
+udevadm settle --timeout ${ROOTDELAY:-30}
+
+# this is taken from 'mountroot' function
+#   see /usr/share/initramfs-tools/scripts/local
+if [ -z "${ROOTFSTYPE}" ]; then
+    FSTYPE=$(get_fstype "${ROOT}")
+else
+    FSTYPE=${ROOTFSTYPE}
+fi
+roflag="-r"
+[ "${readonly}" = "y" ] || roflag="-w"
+mount ${roflag} ${FSTYPE:+-t ${FSTYPE} }${ROOTFLAGS} ${ROOT} ${rootmnt} ||
+	fail "failed to re-mount ${ROOT}. this is bad!"
+
+# vi: ts=4 noexpandtab
